language: node_js
node_js:
  - "10.14"
before_install:
  - npm install -g yarn
branches:
  only:
    - master
    - develop
before_deploy: # 배포하기전 하는 작업들
  - rm -rf node_modules # travis가 설치한 node_moduels를 삭제
  - zip -r simple-blog * # node-koa-server 라는 이름으로 zip 파일 생성
  - mkdir -p deploy # deploy 라는 디렉터리를 만듬
  - mv simple-blog.zip deploy/simple-blog.zip # deploy 디렉터리로 node-koa-server.zip 파일을 이동
deploy: # 배포
  - provider: s3 # AWS S3를 의미
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: simple-blog-cd # S3에 생성한 버킷
    region: us-east-2
    skip_cleanup: true 
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: XxshiftxX/simple-blog
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: simple-blog-cd
    key: simple-blog.zip
    bundle_type: zip
    application: simple-blog-deploy
    deployment_group: simple-blog-deploy-group
    region: us-east-2
    wait-until-deployed: true
    on:
      repo: XxshiftxX/simple-blog
      branch: master
notifications:
  email:
    recipients:
      - contact@dev-shift.me