language: node_js
node_js:
  - "10.14"
before_install:
  - npm install -g yarn
branches:
  only:
    - master
before_deploy:
  - rm -rf node_modules
  - zip -r simple-blog
  - mkdir -p deploy
  - mv simple-blog.zip deploy/simple-blog.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: simple-blog-cd
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: xxshiftxx/simple-blog
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: simple-blog-cd
    key: simple-blog.zip
    bundle_type: zip
    application: simple-blog-deploy
    deployment_group: simple-blog-deploy-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: xxshiftxx/simple-blog
      branch: master
notifications:
  email:
    recipients:
      - qjfrntop12@naver.com